add_newline = false

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"

[directory]
style = "cyan"
read_only = " ğŸ”’"

[git_status]
style = "yellow"

[cmd_duration]
min_time = 1_000
format = "â± [$duration](yellow)"

[time]
disabled = false
format = "ğŸ•’ [$time]($style)"
time_format = "%I:%M:%S %p"
style = "white"

[package]
disabled = true

